### ISSUE TITLE
loos QC Implementation for non-programmers

### ISSUE THREAD

**Issue by gp86041** [ioos/ioos-code-sprint#13]
**Project Description:**

Building an interactive user interface/application based on IOOS QC functions in [https://ioos.github.io/ioos_qc/](https://ioos.github.io/ioos_qc/). QC is important, reducing the complexity of QC process can encourage adoption of IOOS QC by diverse users, and in turn standardized it across broad user groups. Current documentation and code have been developed for programmers and non-programmers may have a hard time using IOOS QC. A possible starting point for this project could be https://github.com/gp86041/IOOS_waterlevel_QC_interactive.

**Expected Outcomes:** 

1. Building an interactive application for non-programmers to upload and QC their data using QARTOD functions.
2. Produce detailed documentation of how to use the application:
- How to import data
- How to use the application
- How to understand the QC flags and further processing

**Skills required:**

Either one of these:
- Basic Python
- Interactive Python
- Application Design

**Difficulty:**

Can vary from easy to difficult depending on skills of group members.

**Topic Lead(s):**

Jeff Pu (gp86041)

**Relevant links:**

[https://ioos.github.io/ioos_qc/](https://ioos.github.io/ioos_qc/)
https://github.com/gp86041/IOOS_waterlevel_QC_interactive

**Comment by joe-smithe-glos** [comment]
@gp86041 Excellent! Thanks for pitching and looking forward to your participation in the Code Sprint. 

For the generic programmers here, what's a QDOT function in this context?

Cheers

-Joe

**Comment by gp86041** [comment]
@joe-smithe-glos Good question! I was thinking about staring with all of them and then narrow down with the group. Current functions on https://github.com/ioos.github.io/loos_qc/ are kinda different in the sense that you can combine multiple quality check/function into a “super function” and then process input data. 

Hope this helps. 

Jeff

**Comment by MathewBiddle** [comment]
page started here: https://ioos.github.io/ioos-code-sprint/topics/07-ioos-qc-non-programmers/

**Comment by kwilcox** [comment]
@gp86041 Did you have any thoughts on what the user interface / application would be? Were you thinking a web application, desktop application, command line application, Jupyter notebook template, etc.?  Could you post examples of what a QDOT function is? I googled around but couldn't come up with anything.

**Comment by joe-smithe-glos** [comment]
On QDOT: was that a typo intended to be QARTOD?

**Comment by gp86041** [comment]
> On QDOT: was that a typo intended to be QARTOD?

@joe-smithe-glos Thank you for pointing that out. I just fixed it in the issue description.

**Comment by joe-smithe-glos** [comment]
OK, good. Appreciate the clarification. Sounded like something relatively new (like Ubidots) so better safe :)

**Comment by jdpye** [comment]
We've done a lot of work with templating QC processes in Jupyter Notebooks. Short advice is: get ready to love widgets. longer advice we can potentially provide once we are more familiar with the specifics of the workflow.

**Comment by abkfenris** [comment]
[Panel] is a nice way to have widgets that lets you start with a notebook and progressively add interactivity and eventually turn it into a dashboard style interface.

Some other similar options are [Streamlit](https://streamlit.io/), [Plotly Dash](https://dash.plotly.com/), and [Voila](https://voila.readthedocs.io/en/stable/index.html).

**Comment by MathewBiddle** [comment]
@gp86041 are you okay giving this sprint pitch on Monday? We are looking for a brief overview of what the topic will be, what slack channel, and what breakout room to join the effort (along with anything else that might be relevant).

**Comment by MathewBiddle** [comment]
Yes, you will be able to pitch virtually. No need for slides. I will bring up the [website](https://ioos.github.io/ioos-code-sprint/topics/07-ioos-qc-non-programmers/) and you can speak to that. Trying to keep it a light lift. Just make sure the appropriate information is in there.

Let me know if you have any questions.
