### ISSUE TITLE
IOOS Compliance Checker sprint topic

### ISSUE THREAD

**Issue by benjwadams** [ioos/ioos-code-sprint#2]
**Replace all _italicized_ text and the issue title with your responses. Remove this text too.**

Project Description:

Compliance Checker refactor and documentation/examples for plugins

_Brief summary of the intent of the project._

Refactor and possibly change the calling conventions of compliance checker.  Make documentation for development of new plugins much easier.  Possibly address OceanGliders 1.0 standard, others as needed.

Expected Outcomes: 

_What do you expect to get out of the project_

Improved documentation for Compliance Checker, improved calling conventions, adaptation of plugins to specific metadata standards such as OG 1.0

Skills required:

Python programming, basic understanding of NetCDF files and associated metadata standards (CF, ACDD, etc).

_What types of skills does the prospective contributor need?_

As above

Difficulty:

Moderate

_Identify the difficulty of the project. [Easy, Moderate, Difficult]_

Topic Lead(s):

Ben Adams

_Include topic lead names and GitHub handles as a comma separated list._

Relevant links:

_Include relevant links to issues/repositories/websites here._

https://github.com/ioos/compliance-checker
https://github.com/ioos/compliance-checker-web
https://github.com/ioos/cc-plugin-glider

**Comment by MathewBiddle** [comment]
@benjwadams I added your content to the website at: https://ioos.github.io/ioos-code-sprint/projects/01-compliance-checker-refactor/
