### ISSUE TITLE
Use GitHub Discussions for project pitches next time?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-code-sprint#22]
What about using [discussions](https://github.com/ioos/ioos-code-sprint/discussions) for project proposals and subsequent conversations? 

See OHW's example: https://github.com/orgs/oceanhackweek/discussions

**Comment by MathewBiddle** [comment]
@ocefpaf how did discussions work for OHW last year? Should we move to that forum or keep with our code sprint project proposal issue [template](https://github.com/ioos/ioos-code-sprint/issues/new/choose).

**Comment by ocefpaf** [comment]
> @ocefpaf how did discussions work for OHW last year? Should we move to that forum or keep with our code sprint project proposal issue [template](https://github.com/ioos/ioos-code-sprint/issues/new/choose)?

I'm not the best person to answer that b/c I did not follow the discussions. I heard it went well. However, as the dinosaur that I am, I don't see any improvement on GH Discussions vs Issues. With that said, don't listen to me and if folks will engage more using discussions, let's give it a go.

**Comment by MathewBiddle** [comment]
I like using issues for now. We have a good template and it seems to be working. We can re-open this if someone really wants to use discussions.
