### ISSUE TITLE
Adding reg link to description

### ISSUE THREAD

**Issue by david-fitch** [ioos/ioos-code-sprint#5]
Hi Mat - just realized it maybe best to add the links for registration and Github website to the description 

https://docs.google.com/forms/d/e/1FAIpQLSeGrLQy9nlWRdNNnffV80sCgUMmd85_n_3iCpiy43GuuY30zw/viewform
https://ioos.github.io/ioos-code-sprint/

**Comment by MathewBiddle** [comment]
Just so I'm clear, you'd like to update the readme.md (stuff the appears when you browse to the repo)? Or the link that appears on the right hand side of the repo?

**Comment by david-fitch** [comment]
Sorry - I think I mean the stuff that appears when you browse the repo. I'm not seeing righthand links. Sorry, I'm not super Git-savvy - here's where I was thinking: 

<img width="1144" alt="Screen Shot 2022-03-11 at 10 09 36 AM" src="https://user-images.githubusercontent.com/52428210/157894196-b9c2ebeb-c9e3-4c02-a449-11ff68c4b8ef.png">
