### ISSUE TITLE
Update participant guide and add to header

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-code-sprint#52]
See the participant guide https://ioos.github.io/ioos-code-sprint/resources/participant-guide/

https://github.com/ioos/ioos-code-sprint/edit/gh-pages/resources/participant-guide.md

We should update it for 2024 and link to the header of the 2024 website.

Should it be a yearly page??

cc: @mwengren

**Comment by MathewBiddle** [comment]
Added https://ioos.github.io/ioos-code-sprint/2024/participant-guide

![image](https://github.com/ioos/ioos-code-sprint/assets/8480023/defcceaa-140f-4bb5-bbf3-f7469df34bf2)

@mwengren please review the page and close this issue if you're comfortable with it.

**Comment by mwengren** [comment]
It looks good to me!  We can update if needed before next week.
